# Fabric Properties
# Check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17.21
java_version=25

# Dependencies
fabric_version=0.161.0+26.3
modmenu_version=21.0.0

# fabric.mod.json dependency ranges
loader_dependency=>=0.19.5
minecraft_dependency=>=26.3 <26.4
java_dependency=>=25
fabric_api_dependency=*
